name: test

on:
    release:
        types: [published]

env:
    RELEASE_VERSION: ${{ github.event.release.tag_name }}
    COMMIT_SHA: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}   
      - name: print
        run: |
            printf "${{ env.RELEASE_VERSION}}"
            printf "${{ env.COMMIT_SHA }}"
      - name: print 2
        run: |
            SHORT_SHA=${COMMIT_SHA:0:8}
            echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
            printf "SHORT_SHA"
      - name: print 3
        run: |
            SHORT_S=$(git rev-parse --short=8 HEAD)
            echo "SHORT_S=$SHORT_S" >> "$GITHUB_ENV_SHA"
            printf "SHORT_S"
            